service: auth
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  register:
    handler: index.register
    events:
      - http:
          path: auth/register
          method: post
          cors:
          origin: '*'
          headers:
            - content-type

  login:
    handler: index.login
    events:
      - http:
          path: auth/login
          method: post
          cors:
          origin: '*'
          headers:
            - content-type
  
  forgotPassword:
    handler: index.forgotPassword
    events:
      - http:
          path: auth/forgotPassword
          method: post
          cors:
          origin: '*'
          headers:
            - content-type

  confirmPassword:
    handler: index.confirmPassword
    events:
      - http:
          path: auth/confirmPassword
          method: post
          cors:
          origin: '*'
          headers:
            - content-type

# you can add CloudFormation resource templates here
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'content-type'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

plugins:
  - serverless-offline
